[0m14:44:22.724470 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002019781CC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002019781F3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020197EDC0D0>]}


============================== 14:44:22.731488 | 5a91da1f-cd52-4a1e-8be1-f6d40f307c90 ==============================
[0m14:44:22.731488 [info ] [MainThread]: Running with dbt=1.7.4
[0m14:44:22.732467 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nandh\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m14:45:05.907235 [debug] [MainThread]: Starter project path: C:\Users\nandh\dbt_ws\dbt_core\Lib\site-packages\dbt\include\starter_project
[0m14:45:06.019889 [info ] [MainThread]: 
Your new dbt project "dbt_uniper" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:45:06.023886 [info ] [MainThread]: Setting up your profile.
[0m14:51:31.916936 [info ] [MainThread]: Profile dbt_uniper written to C:\Users\nandh\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:51:31.921172 [debug] [MainThread]: Command `dbt init` succeeded at 14:51:31.921172 after 429.29 seconds
[0m14:51:31.923167 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002019781F3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002019781E590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002019781D2D0>]}
[0m14:51:31.925168 [debug] [MainThread]: Flushing usage events
[0m14:57:51.681175 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000171CBCCE090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000171CB3A0590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000171CB7D4F10>]}


============================== 14:57:51.691190 | 8d223a64-49c8-4e8d-aaac-fd3eb1a466b5 ==============================
[0m14:57:51.691190 [info ] [MainThread]: Running with dbt=1.7.4
[0m14:57:51.694165 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\nandh\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:57:51.696166 [info ] [MainThread]: dbt version: 1.7.4
[0m14:57:51.697186 [info ] [MainThread]: python version: 3.11.6
[0m14:57:51.699162 [info ] [MainThread]: python path: C:\Users\nandh\dbt_ws\dbt_core\Scripts\python.exe
[0m14:57:51.701161 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m14:57:52.662984 [info ] [MainThread]: Using profiles dir at C:\Users\nandh\.dbt
[0m14:57:52.664983 [info ] [MainThread]: Using profiles.yml file at C:\Users\nandh\.dbt\profiles.yml
[0m14:57:52.666983 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nandh\dbt_ws\dbt_project.yml
[0m14:57:52.669982 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:57:52.673978 [debug] [MainThread]: Command `dbt debug` failed at 14:57:52.673978 after 1.10 seconds
[0m14:57:52.674977 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000171CBD1D910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000171CBD1D9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000171CB8DABD0>]}
[0m14:57:52.676978 [debug] [MainThread]: Flushing usage events
[0m11:01:19.402092 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1CBFD3310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1CBBA3650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1CBFC7010>]}


============================== 11:01:19.411120 | 774f0045-6dd8-436a-858f-4068e7f99c1b ==============================
[0m11:01:19.411120 [info ] [MainThread]: Running with dbt=1.7.4
[0m11:01:19.413046 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nandh\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt compile -s my_first_dbt_model', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:01:19.414053 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nandh\dbt_ws\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:01:19.416042 [debug] [MainThread]: Command `dbt compile` failed at 11:01:19.416042 after 0.11 seconds
[0m11:01:19.418039 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1CB800150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1CBF89690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1CB7EC150>]}
[0m11:01:19.420041 [debug] [MainThread]: Flushing usage events
[0m11:02:37.199881 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF237B6250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF23010090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF23275690>]}


============================== 11:02:37.207897 | 4d9fdb6f-174e-49dc-8213-ce673eff7a4d ==============================
[0m11:02:37.207897 [info ] [MainThread]: Running with dbt=1.7.4
[0m11:02:37.208874 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nandh\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt compile -s my_first_dbt_model', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:02:37.210872 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nandh\dbt_ws\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:02:37.213894 [debug] [MainThread]: Command `dbt compile` failed at 11:02:37.213894 after 0.09 seconds
[0m11:02:37.214893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF232C81D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF23778FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF22FF0F50>]}
[0m11:02:37.215893 [debug] [MainThread]: Flushing usage events
